### ISSUE TITLE
Github Action fails

### ISSUE THREAD

**Issue by svenmueller** [tsuyoshicho/action-textlint#37]
Hi,

I tried the following example configuration from the README.md

```
name: reviewdog
on: [pull_request]
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
```

The github action action fails with:
```
/usr/bin/docker run --name yxz --label 430c1a --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_REPORTER -e INPUT_LEVEL -e INPUT_TEXTLINT_FLAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/k8s-manifests/k8s-manifests":"/github/workspace" 430c1a:c6d9dff969014135bcaebd57d1067df8  "***" "error" "github-pr-review" "."
npm WARN saveError ENOENT: no such file or directory, open '/github/workspace/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/github/workspace/package.json'
npm WARN workspace No description
npm WARN workspace No repository field.
npm WARN workspace No README data
npm WARN workspace No license field.

up to date in 0.525s
found 0 vulnerabilities

/entrypoint.sh: line 11: /github/workspace/node_modules/.bin/textlint: not found
/entrypoint.sh: line 13: /github/workspace/node_modules/.bin/textlint: not found
reviewdog: parse error: EOF
```

Any idea why this happens?

Thx,
Sven
