### ISSUE TITLE
fail-on-error has been deprecated

### ISSUE THREAD

**Issue by justin-p** [tsuyoshicho/action-textlint#524]
fail-on-error has been [deprecated](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md#rotating_light-deprecation-warnings). When used in this action, it gives the following warning and results in a non zero exit code, making the action fail.

```bash
[...SNIP...]
 Running textlint fixing report 🐶 ...
  No local changes to save
  time=2025-05-14T08:14:19.216Z level=WARN msg="reviewdog: -fail-on-error is deprecated. Use -fail-level=any, or -fail-level=error for github-[pr-]check reporter instead. See also https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md"
  No stash entries found.
Error: Process completed with exit code 1.
```

```yaml
[...SNIP...]
jobs:
  textlint:
    name: Textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create package-lock.json
        run: npm install --package-lock-only
      - name: textlint
        uses: tsuyoshicho/action-textlint@v3
        with:
          fail_on_error: true
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
```
